# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2



class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveTesting = channel.unary_unary(
                '/TestService/SaveTesting',
                request_serializer=test__pb2.Test.SerializeToString,
                response_deserializer=test__pb2.saveTestResponse.FromString,
                )
        self.GetTesting = channel.unary_unary(
                '/TestService/GetTesting',
                request_serializer=test__pb2.Empty.SerializeToString,
                response_deserializer=test__pb2.getTestResponse.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveTesting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTesting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveTesting': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTesting,
                    request_deserializer=test__pb2.Test.FromString,
                    response_serializer=test__pb2.saveTestResponse.SerializeToString,
            ),
            'GetTesting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTesting,
                    request_deserializer=test__pb2.Empty.FromString,
                     response_serializer=test__pb2.getTestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveTesting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestService/SaveTesting',
            test__pb2.Test.SerializeToString,
            test__pb2.saveTestResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTesting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestService/GetTesting',
            test__pb2.Empty.SerializeToString,
            test__pb2.getTestResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
